version: "3"

services:
  open-math-prep-dev:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
      target: dev
    image: open-math-prep-dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
        - ../../:/app
        - /app/node_modules
        - /app/.next