create table "public"."profile_topics" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "topic_id" bigint,
    "profile_id" uuid
);


alter table "public"."profile_topics" enable row level security;

create table "public"."topics" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "topic_name" text
);


alter table "public"."topics" enable row level security;

alter table "public"."profiles" add column "subscribed_topics" bigint[];

CREATE UNIQUE INDEX profile_topics_pkey ON public.profile_topics USING btree (id);

CREATE UNIQUE INDEX topics_pkey ON public.topics USING btree (id);

CREATE UNIQUE INDEX topics_topic_name_key ON public.topics USING btree (topic_name);

alter table "public"."profile_topics" add constraint "profile_topics_pkey" PRIMARY KEY using index "profile_topics_pkey";

alter table "public"."topics" add constraint "topics_pkey" PRIMARY KEY using index "topics_pkey";

alter table "public"."profile_topics" add constraint "profile_topics_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_topics" validate constraint "profile_topics_profile_id_fkey";

alter table "public"."profile_topics" add constraint "profile_topics_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES topics(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_topics" validate constraint "profile_topics_topic_id_fkey";

alter table "public"."topics" add constraint "topics_topic_name_key" UNIQUE using index "topics_topic_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

grant delete on table "public"."profile_topics" to "anon";

grant insert on table "public"."profile_topics" to "anon";

grant references on table "public"."profile_topics" to "anon";

grant select on table "public"."profile_topics" to "anon";

grant trigger on table "public"."profile_topics" to "anon";

grant truncate on table "public"."profile_topics" to "anon";

grant update on table "public"."profile_topics" to "anon";

grant delete on table "public"."profile_topics" to "authenticated";

grant insert on table "public"."profile_topics" to "authenticated";

grant references on table "public"."profile_topics" to "authenticated";

grant select on table "public"."profile_topics" to "authenticated";

grant trigger on table "public"."profile_topics" to "authenticated";

grant truncate on table "public"."profile_topics" to "authenticated";

grant update on table "public"."profile_topics" to "authenticated";

grant delete on table "public"."profile_topics" to "service_role";

grant insert on table "public"."profile_topics" to "service_role";

grant references on table "public"."profile_topics" to "service_role";

grant select on table "public"."profile_topics" to "service_role";

grant trigger on table "public"."profile_topics" to "service_role";

grant truncate on table "public"."profile_topics" to "service_role";

grant update on table "public"."profile_topics" to "service_role";

grant delete on table "public"."topics" to "anon";

grant insert on table "public"."topics" to "anon";

grant references on table "public"."topics" to "anon";

grant select on table "public"."topics" to "anon";

grant trigger on table "public"."topics" to "anon";

grant truncate on table "public"."topics" to "anon";

grant update on table "public"."topics" to "anon";

grant delete on table "public"."topics" to "authenticated";

grant insert on table "public"."topics" to "authenticated";

grant references on table "public"."topics" to "authenticated";

grant select on table "public"."topics" to "authenticated";

grant trigger on table "public"."topics" to "authenticated";

grant truncate on table "public"."topics" to "authenticated";

grant update on table "public"."topics" to "authenticated";

grant delete on table "public"."topics" to "service_role";

grant insert on table "public"."topics" to "service_role";

grant references on table "public"."topics" to "service_role";

grant select on table "public"."topics" to "service_role";

grant trigger on table "public"."topics" to "service_role";

grant truncate on table "public"."topics" to "service_role";

grant update on table "public"."topics" to "service_role";


