create table "public"."lectureprogress" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "progress" smallint,
    "name" text,
    "user_id" uuid default gen_random_uuid()
);


alter table "public"."lectureprogress" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "username" text,
    "full_name" text,
    "avatar_url" text,
    "email" text
);


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX lectureprogress_pkey ON public.lectureprogress USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

alter table "public"."lectureprogress" add constraint "lectureprogress_pkey" PRIMARY KEY using index "lectureprogress_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."lectureprogress" add constraint "lectureprogress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."lectureprogress" validate constraint "lectureprogress_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(username) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
  insert into public.profiles (id, full_name, avatar_url,email,username)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url',new.email,new.raw_user_meta_data->>'nickname');
  return new;
end;$function$
;

grant delete on table "public"."lectureprogress" to "anon";

grant insert on table "public"."lectureprogress" to "anon";

grant references on table "public"."lectureprogress" to "anon";

grant select on table "public"."lectureprogress" to "anon";

grant trigger on table "public"."lectureprogress" to "anon";

grant truncate on table "public"."lectureprogress" to "anon";

grant update on table "public"."lectureprogress" to "anon";

grant delete on table "public"."lectureprogress" to "authenticated";

grant insert on table "public"."lectureprogress" to "authenticated";

grant references on table "public"."lectureprogress" to "authenticated";

grant select on table "public"."lectureprogress" to "authenticated";

grant trigger on table "public"."lectureprogress" to "authenticated";

grant truncate on table "public"."lectureprogress" to "authenticated";

grant update on table "public"."lectureprogress" to "authenticated";

grant delete on table "public"."lectureprogress" to "service_role";

grant insert on table "public"."lectureprogress" to "service_role";

grant references on table "public"."lectureprogress" to "service_role";

grant select on table "public"."lectureprogress" to "service_role";

grant trigger on table "public"."lectureprogress" to "service_role";

grant truncate on table "public"."lectureprogress" to "service_role";

grant update on table "public"."lectureprogress" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

create policy "Enable delete for users based on user_id"
on "public"."lectureprogress"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable insert for users based on user_id"
on "public"."lectureprogress"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));


create policy "enable read for users based on user_id"
on "public"."lectureprogress"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Public profiles are viewable by everyone."
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Users can insert their own profile."
on "public"."profiles"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Users can update own profile."
on "public"."profiles"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = id));



